# Generated by Django 3.1 on 2020-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('field_1', models.IntegerField(default=1)),
                ('field_2', models.IntegerField(default=1)),
                ('field_3', models.IntegerField(default=1)),
                ('field_4', models.IntegerField(default=1)),
                ('field_5', models.IntegerField(default=1)),
                ('field_6', models.IntegerField(default=1)),
            ],
        ),
    ]
